# Numpy 101

The goal of this challenge is to get familiar with the Numpy library, manipulate multidimensional arrays and apply some linear algebra operations without using `for` loops.

💡 Do not forget to keep the [Numpy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf) closed during this challenge.

In [33]:
import numpy as np # Run this cell!


---

**Q1** - Create a null vector (i.e. with only zeros `0`) of size 10 and assign it to a variable named `ten_zeros`. 

It should look like this:

```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.zeros.html"><code>numpy.zeros</code></a></p>
</details>

In [34]:
ten_zeros = np.zeros(10)

print(ten_zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


---

**Q2** - Create a vector with values from 5 to 10 and assign it to a variable named `five_to_ten`.

It should look like this:

```
array([ 5,  6,  7,  8,  9, 10])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.arange.html"><code>numpy.arange</code></a></p>
</details>

In [35]:
five_to_ten = np.array([5, 6, 7, 8, 9, 10])

print(five_to_ten)


[ 5  6  7  8  9 10]


---

**Q3** - Create the following matrix as a NumPy `ndarray` and assign it to a variable named `A`:

$
A = 
\begin{pmatrix}
5 & 9 & 7\\
1 & 0 & 3
\end{pmatrix}
$

<br>
<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.array.html"><code>numpy.array</code></a></p>
    <p>Checkout more about the relationship between<a href="https://stackoverflow.com/questions/15879315/what-is-the-difference-between-ndarray-and-array-in-numpy"><code>numpy.array and numpy.ndarray</code></a></p>
</details>

In [36]:
A = np.array([[5, 9, 7], [1, 0, 3]])

print(A)


[[5 9 7]
 [1 0 3]]


---
**Q4** - Create the following matrix without using the `np.array()` constructor and assign it to a variable named `B`:

$
B = 
\begin{pmatrix}
1 & 1\\
1 & 1
\end{pmatrix}
$

In [37]:
B = np.array([[1, 1], [1, 1]])

print(B)


[[1 1]
 [1 1]]


---

**Q5** - Create a vector of 20 elements evenly spaced between `-1` and `1` and assign it to a variable named `lin_twenty`.

It should look like this:

```
array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])
```

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.linspace.html"><code>numpy.linspace</code></a></p>
</details>

In [38]:
lin_twenty = np.linspace(-1, 1, 20)

print(lin_twenty)


[-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ]


---

**Q6** - Create a 3x3 identity matrix and assign it to a variable named `C`:

$
C = 
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.eye.html"><code>numpy.eye</code></a></p>
</details>

In [39]:
C = np.identity(3)

print(C)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


---

**Q7** - Create the following `ndarray` and assign it to a variable named `D`:  

$
D = 
\begin{pmatrix}
2 & 9 & 7 & 3 & 1 & 5
\end{pmatrix}
$

Reshape `D` into a 2x3 matrix and assign it to a variable named `E`:

$
E = 
\begin{pmatrix}
2 & 9 & 7\\
3 & 1 & 5
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.reshape.html"><code>numpy.reshape</code></a></p>
</details>

In [48]:
D = np.array([2, 9, 7, 3, 1, 5])

E = D.reshape(2, 3)

print(E)


[[2 9 7]
 [3 1 5]]


---

**Q8** - Create a 8x8 checkboard matrix and assign it to a variable named `F`:

$
F = 
\begin{pmatrix}
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0\\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1\\
\end{pmatrix}
$

<br>

<details>
    <summary>🆘 Hint</summary>
    <p>Have a look at <a href="https://numpy.org/devdocs/reference/generated/numpy.tile.html"><code>numpy.tile</code></a></p>
</details>

In [41]:
F = np.zeros((8, 8), dtype=int)
F[1::2, ::2] = 1
F[::2, 1::2] = 1

print(F)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


---

**Q9**: Select the second column of this `ndarray` `G`, reshape it as an `ndarray` of 4 lines and 1 column and assign it to a variable named `reshaped_G`:

$
reshaped\_G = 
\begin{pmatrix}
0.?\\
0.?\\
0.?\\
0.?\\
\end{pmatrix}
$

In [42]:
G = np.random.random((4, 5))
print(G)


[[0.31375162 0.99420716 0.9035885  0.21828001 0.99582557]
 [0.31262024 0.29519738 0.78436282 0.68275175 0.01771849]
 [0.91693634 0.18534372 0.24628191 0.13836677 0.3126841 ]
 [0.70022449 0.47454441 0.74340512 0.87985635 0.94733761]]


In [43]:
G = np.random.random((4, 5))

print("G:")
print(G)

second_column = G[:, 1]
reshaped_G = second_column.reshape(4, 1)

print("\nreshaped_G:")
print(reshaped_G)


G:
[[0.06318746 0.60766982 0.61881267 0.53004929 0.64531727]
 [0.0245071  0.16272552 0.26029525 0.02431508 0.9596658 ]
 [0.69861056 0.40134001 0.28315141 0.79517689 0.77064269]
 [0.66650644 0.7040496  0.66372795 0.83151591 0.68522361]]

reshaped_G:
[[0.60766982]
 [0.16272552]
 [0.40134001]
 [0.7040496 ]]


---

**Q10** - Compute the sum of matrixes `H` and `I` and store the result into a variable `hi_sum`:

$
H = 
\begin{pmatrix}
0 & 4\\
-4 & -3\\
1 & 1
\end{pmatrix}
$

$
I =
\begin{pmatrix}
0 & 1\\
1 & -1\\
2 & 3
\end{pmatrix}
$

$
H + I = ?
$


In [44]:
# Here we demonstrate two different approaches to creating a (3,2) Matrix
H = np.array([0, 4, -4, -3, 1, 1]).reshape(3, 2)
print('H: \n', H)
I = np.array([[0, 1], [1, -1], [2, 3]])
print('I: \n', I)


H: 
 [[ 0  4]
 [-4 -3]
 [ 1  1]]
I: 
 [[ 0  1]
 [ 1 -1]
 [ 2  3]]


In [45]:
H = np.array([0, 4, -4, -3, 1, 1]).reshape(3, 2)
print('H:\n', H)

I = np.array([[0, 1], [1, -1], [2, 3]])
print('I:\n', I)

hi_sum = H + I
print('Sum of H and I:\n', hi_sum)


H:
 [[ 0  4]
 [-4 -3]
 [ 1  1]]
I:
 [[ 0  1]
 [ 1 -1]
 [ 2  3]]
Sum of H and I:
 [[ 0  5]
 [-3 -4]
 [ 3  4]]


## Check your code!

Run the cell below to check your code:

In [46]:
from nbresult import ChallengeResult

result = ChallengeResult('numpy',
    ten=ten_zeros,
    from_five=five_to_ten,
    A=A,
    B=B,
    lin_twenty=lin_twenty,
    C=C,
    E=E,
    F=F,
    reshaped_G=reshaped_G,
    hi_sum=hi_sum
)
result.write()
print(result.check())



============================= test session starts ==============================
platform darwin -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0 -- /Users/reecepalmer/.pyenv/versions/3.10.6/envs/lewagon/bin/python3
cachedir: .pytest_cache
rootdir: /Users/reecepalmer/Code/RPalmr/02-Data-Toolkit/01-Data-Analysis/data-numpy/tests
plugins: asyncio-0.19.0, dash-2.14.0, typeguard-4.1.5, anyio-3.6.2, hydra-core-1.3.2
asyncio: mode=strict
collecting ... collected 5 items

test_numpy.py::TestNumpy::test_advanced_matrixes_manipulation PASSED     [ 20%]
test_numpy.py::TestNumpy::test_linear_twenty_vector_creation PASSED      [ 40%]
test_numpy.py::TestNumpy::test_matrixes_creation_and_reshaping FAILED    [ 60%]
test_numpy.py::TestNumpy::test_ndarrays_creation PASSED                  [ 80%]
test_numpy.py::TestNumpy::test_vectors_creation PASSED                   [100%]

=================================== FAILURES ===================================
________________ TestNumpy.test_matrixes_creation_a

In [47]:
from nbresult import ChallengeResult

result = ChallengeResult('numpy',
    ten=ten_zeros,
    from_five=five_to_ten,
    A=A,
    B=B,
    lin_twenty=lin_twenty,
    C=C,
    E=E,
    F=F,
    reshaped_G=reshaped_G,
    hi_sum=hi_sum
)
result.write()
print(result.check())



============================= test session starts ==============================
platform darwin -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0 -- /Users/reecepalmer/.pyenv/versions/3.10.6/envs/lewagon/bin/python3
cachedir: .pytest_cache
rootdir: /Users/reecepalmer/Code/RPalmr/02-Data-Toolkit/01-Data-Analysis/data-numpy/tests
plugins: asyncio-0.19.0, dash-2.14.0, typeguard-4.1.5, anyio-3.6.2, hydra-core-1.3.2
asyncio: mode=strict
collecting ... collected 5 items

test_numpy.py::TestNumpy::test_advanced_matrixes_manipulation PASSED     [ 20%]
test_numpy.py::TestNumpy::test_linear_twenty_vector_creation PASSED      [ 40%]
test_numpy.py::TestNumpy::test_matrixes_creation_and_reshaping FAILED    [ 60%]
test_numpy.py::TestNumpy::test_ndarrays_creation PASSED                  [ 80%]
test_numpy.py::TestNumpy::test_vectors_creation PASSED                   [100%]

=================================== FAILURES ===================================
________________ TestNumpy.test_matrixes_creation_a